import { Poppins } from "next/font/google";
import "./globals.css";
import AOSProvider from "./AOSProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"], // pesos que necesites
  variable: "--font-poppins",    // CSS variable opcional
});

export const metadata = {
  title: "Muebleria Jose",
  description: "Generated by GoatCrazy9",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${poppins.variable} antialiased`}>
        <AOSProvider>{children}</AOSProvider>
      </body>
    </html>
  );
}
